version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - /c/Users/sunil/Desktop/taskProcesser/logs:/usr/src/app/logs  # Mounting Windows directory to container

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
